// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcVCVI7EtnIBfX2yFb7BvXXDsFKsnXAEM',
    appId: '1:546536198198:web:4bf70970ccb71931b5c897',
    messagingSenderId: '546536198198',
    projectId: 'shoes-53468',
    authDomain: 'shoes-53468.firebaseapp.com',
    storageBucket: 'shoes-53468.firebasestorage.app',
    measurementId: 'G-6B5MZ3GKY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS0J9lgtOU-bjOmpRapxR27Y2LeiwRAhE',
    appId: '1:546536198198:android:854a864257a1cf9fb5c897',
    messagingSenderId: '546536198198',
    projectId: 'shoes-53468',
    storageBucket: 'shoes-53468.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDABSrRwIcgpIhvhLny5EOI596sqaBhPgk',
    appId: '1:546536198198:ios:31ed9e8afbfebdd5b5c897',
    messagingSenderId: '546536198198',
    projectId: 'shoes-53468',
    storageBucket: 'shoes-53468.firebasestorage.app',
    iosBundleId: 'com.example.shoes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcVCVI7EtnIBfX2yFb7BvXXDsFKsnXAEM',
    appId: '1:546536198198:web:70db38ab78058812b5c897',
    messagingSenderId: '546536198198',
    projectId: 'shoes-53468',
    authDomain: 'shoes-53468.firebaseapp.com',
    storageBucket: 'shoes-53468.firebasestorage.app',
    measurementId: 'G-HW6ND24Q0N',
  );
}
